### ISSUE TITLE
[Stackoverflow] Google Finance scrape price % change

### ISSUE THREAD

**Issue by dimitryzub** [dimitryzub/stackoverflow-answers-archive#13]
Question: https://stackoverflow.com/questions/68974452/pulling-current-price-change-google-finance-with-google-apps-script

**Comment by Mykhailo-Zub** [comment]
> Question: https://stackoverflow.com/questions/68974452/pulling-current-price-change-google-finance-with-google-apps-script

@dimitryzub I don't see Google Finance API from SerpApi to add SerpApi solution to my possible answer.

**Comment by dimitryzub** [comment]
@Mykhailo-Zub Yes, it's true. 

In such cases, you can add a link to serpapi/blog which has a [Google Finance blog post](https://serpapi.com/blog/scrape-google-finance-ticker-quote-data-in-python/) and say something like: "_If you want to make a Python parser, have a look at dedicated blog post <name of the blog post> at SerpApi_". 

To sum up, if there's no supported API on SerpApi, but there's a blog post about it, we can always mention it which generates some additional traffic and users that potentially were looking for a particular solution.
