### ISSUE TITLE
[Twitter] - Google Scholar Scrape 100 pages from organic results

### ISSUE THREAD

**Issue by vikakudinska** [dimitryzub/stackoverflow-answers-archive#6]
Tweet link: https://twitter.com/nealhaddaway/status/1314225954022195203

Answer:
Hey, you can do it more simply.
If someone want to srcape Google Scholar from organic results in Python I can suggest a link SerpApi https://serpapi.com/google-scholar-organic-results

**Comment by dimitryzub** [comment]
> Hey, you can do it more simply.
If someone want to srcape Google Scholar from organic results in Python I can suggest a link SerpApi https://serpapi.com/google-scholar-organic-results
___
Suggestion:
Hey, if you're using Python you can do it more simply by using Google Scholar Organic Results API from SerpApi which is a paid API with a free plan. 

Docs: https://serpapi.com/google-scholar-organic-results
Playground: https://serpapi.com/playground?engine=google_scholar&q=biology
